version: '3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9000:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - mynetwork

  

networks:
  mynetwork:

